"""Verify platform node audit logs.

Checks performed:
- JSON record structure
- hash-chain continuity
- recomputed record hash
- Ed25519 signature over each record hash
- public key id consistency
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from secure_dfl_platform.crypto import (
    canonical_json_bytes,
    load_public_key_b64,
    public_key_id,
    trusted_keys_from_file,
    verify_b64,
)


def verify_audit_file(path: Path, trusted_keys_file: Path | None) -> dict[str, Any]:
    trusted_keys = trusted_keys_from_file(trusted_keys_file) if trusted_keys_file else {}
    trust_source = "trusted_keys_file" if trusted_keys_file else "audit_log_node_started"
    records = [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    errors: list[str] = []
    previous_hash = "GENESIS"
    event_counts: dict[str, int] = {}
    partial_finalizations = 0

    for index, signed_record in enumerate(records, start=1):
        node_id = str(signed_record.get("node_id", ""))
        event_type = str(signed_record.get("event_type", ""))
        event_counts[event_type] = event_counts.get(event_type, 0) + 1
        details = signed_record.get("details", {})
        if (
            trusted_keys_file is None
            and event_type == "node_started"
            and isinstance(details, dict)
            and "public_key" in details
            and node_id not in trusted_keys
        ):
            trusted_keys[node_id] = load_public_key_b64(str(details["public_key"]))
        if isinstance(details, dict) and details.get("partial_finalization"):
            partial_finalizations += 1

        if signed_record.get("previous_hash") != previous_hash:
            errors.append(
                f"{path}: line {index}: previous_hash mismatch; "
                f"expected {previous_hash}, got {signed_record.get('previous_hash')}"
            )

        unsigned_record = {
            key: value
            for key, value in signed_record.items()
            if key not in {"record_hash", "public_key_id", "signature_b64"}
        }
        expected_hash = __import__("hashlib").sha256(
            canonical_json_bytes(unsigned_record)
        ).hexdigest()
        if signed_record.get("record_hash") != expected_hash:
            errors.append(f"{path}: line {index}: record_hash mismatch")

        public_key = trusted_keys.get(node_id)
        if public_key is None:
            errors.append(f"{path}: line {index}: missing trusted key for {node_id}")
        else:
            if signed_record.get("public_key_id") != public_key_id(public_key):
                errors.append(f"{path}: line {index}: public_key_id mismatch")
            if not verify_b64(
                public_key,
                str(signed_record.get("record_hash", "")).encode("ascii"),
                str(signed_record.get("signature_b64", "")),
            ):
                errors.append(f"{path}: line {index}: invalid signature")

        previous_hash = str(signed_record.get("record_hash", ""))

    return {
        "path": str(path),
        "valid": not errors,
        "records": len(records),
        "last_hash": previous_hash,
        "event_counts": event_counts,
        "partial_finalizations": partial_finalizations,
        "trust_source": trust_source,
        "errors": errors,
    }


def discover_audit_logs(runtime_dir: Path) -> list[Path]:
    if runtime_dir.is_file():
        return [runtime_dir]
    return sorted(runtime_dir.rglob("node_audit.jsonl"))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify Secure DFL platform audit logs")
    parser.add_argument(
        "--runtime-dir",
        required=True,
        help="Runtime/results directory or a single node_audit.jsonl file",
    )
    parser.add_argument(
        "--trusted-keys",
        default="",
        help="Path to trusted_keys.json generated by keygen.py",
    )
    parser.add_argument(
        "--output",
        default="",
        help="Optional JSON report path",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    runtime_dir = Path(args.runtime_dir)
    trusted_keys_file = Path(args.trusted_keys) if args.trusted_keys else None
    logs = discover_audit_logs(runtime_dir)
    if not logs:
        raise SystemExit(f"No node_audit.jsonl files found under {runtime_dir}")

    results = [verify_audit_file(path, trusted_keys_file) for path in logs]
    report = {
        "status": "PASS" if all(item["valid"] for item in results) else "FAIL",
        "audit_logs_checked": len(results),
        "total_records": sum(int(item["records"]) for item in results),
        "partial_finalizations": sum(
            int(item["partial_finalizations"]) for item in results
        ),
        "results": results,
    }
    payload = json.dumps(report, indent=2, sort_keys=True)
    if args.output:
        Path(args.output).write_text(payload, encoding="utf-8")
    print(payload)
    if report["status"] != "PASS":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
